version: '2.1'

services:
  b1:
    build: ./bgp/.
    volumes:
      - ./volumes/bgp/b1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b1/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./resolv.conf:/etc/resolv.conf
    image: bgp:20180426
    privileged: true
    ports:
      #admin
      - 10201:2601
      #ospf ipv6
      - 10203:2606
      #bgp
      - 10204:2605
      #- 53:53
      #- 443:443
    networks:
      redD:
        ipv6_address: 2001:d:1::10
      red3:
        ipv6_address: 2001:a:3::3

  r3:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10014:2601
      #ospf ipv6
      - 10034:2606
    networks:
      red2:
        ipv6_address: 2001:a:2::10
      red3:
        ipv6_address: 2001:a:3::4
      red4:
        ipv6_address: 2001:a:4::10
     
  r5:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r5/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r5/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10016:2601
      #ospf ipv6
      - 10036:2606
    networks:
      red3:
        ipv6_address: 2001:a:3::2
      red5:
        ipv6_address: 2001:a:5::10
      red7:
        ipv6_address: 2001:a:7::10

  r7:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r7/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r7/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10018:2601
      #ospf ipv6
      - 10038:2606
    networks:
      red3:
        ipv6_address: 2001:a:3::5
      red6:
        ipv6_address: 2001:a:6::10
      red7:
        ipv6_address: 2001:a:7::20

  
  h11:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./client:/client
      - ./resolv.conf:/etc/resolv.conf
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10021:2601
      #ospf ipv6
      - 10041:2606
    networks:
      red5:
        ipv6_address: 2001:a:5::20

 
  h13:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./client:/client
      - ./resolv.conf:/etc/resolv.conf
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10023:2601
      #ospf ipv6
      - 10043:2606
    networks:
      red6:
        ipv6_address: 2001:a:6::20

  
networks:
  redD:
    external:
      name: redD
  red2:
    external:
      name: red2
  red3:
    external:
      name: red3
  red4:
    external:
      name: red4
  red5:
    external:
      name: red5
  red6:
    external:
      name: red6
  red7:
    external:
      name: red7
 
