version: '2.1'

services:
  b2:
    build: ./bgp/.
    volumes:
      - ./volumes/bgp/b2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b2/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./resolv.conf:/etc/resolv.conf
    image: bgp:20180426
    privileged: true
    ports:
      #admin
      - 10201:2601
      #ospf ipv6
      - 10203:2606
      #bgp
      - 10204:2605
      #- 53:53
      #- 443:443
    networks:
      redD:
        ipv6_address: 2001:d:1::20
      red3:
        ipv6_address: 2001:b:3::3

  r4:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10014:2601
      #ospf ipv6
      - 10034:2606
    networks:
      red2:
        ipv6_address: 2001:b:2::10
      red3:
        ipv6_address: 2001:b:3::4
      red4:
        ipv6_address: 2001:b:4::10
     
  r6:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r6/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r6/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10016:2601
      #ospf ipv6
      - 10036:2606
    networks:
      red3:
        ipv6_address: 2001:b:3::2
      red5:
        ipv6_address: 2001:b:5::10
      red7:
        ipv6_address: 2001:b:7::10

  r8:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r8/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r8/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10018:2601
      #ospf ipv6
      - 10038:2606
    networks:
      red3:
        ipv6_address: 2001:b:3::5
      red6:
        ipv6_address: 2001:b:6::10
      red7:
        ipv6_address: 2001:b:7::20

  
  h12:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./client:/client
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10021:2601
      #ospf ipv6
      - 10041:2606
    networks:
      red5:
        ipv6_address: 2001:b:5::20

 
  h14:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./client:/client
      - ./resolv.conf:/etc/resolv.conf
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10023:2601
      #ospf ipv6
      - 10043:2606
    networks:
      red6:
        ipv6_address: 2001:b:6::20

  
networks:
  redD:
    external:
      name: redD
  red2:
    external:
      name: red2
  red3:
    external:
      name: red3
  red4:
    external:
      name: red4
  red5:
    external:
      name: red5
  red6:
    external:
      name: red6
  red7:
    external:
      name: red7
 
